### ISSUE TITLE
Dependency on user email

### ISSUE THREAD

**Issue by verwilst** [ingria/laravel-x509-auth#1]
Because the email field is hardcoded as searchfield, it's impossible for the user to change his email address without generating a new certificate. Maybe there's a possibility to configure a lookup to another field ( username for example ), to make it more flexible?

**Comment by ingria** [comment]
You can now extend the base class and implement your own auth logic ([docs](https://github.com/ingria/laravel-x509-auth/wiki/Using-other-cert-attributes)).

Not sure if there's another way to allow customization without making a mess 🤔
